import type { ContentItem } from './types'

const NOW = '2026-04-26T06:00:00.000Z'

export const MOCK_ITEMS: ContentItem[] = [
  // ── Startups ─────────────────────────────────────────────────────────────
  {
    id: 's1',
    source_type: 'youtube',
    source_name: 'Y Combinator',
    category: 'startups',
    title: 'How Sequoia Thinks About Early-Stage Investing in 2026',
    excerpt: "Roelof Botha breaks down the firm's current thesis, why European founders are increasingly on their radar, and what separates a $10M seed from a $100M Series A.",
    url: 'https://www.youtube.com/watch?v=mock-s1',
    thumbnail_url: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&q=80',
    author: 'Y Combinator',
    duration: 3847,
    published_at: '2026-04-26T04:12:00.000Z',
    fetched_at: NOW,
    created_at: NOW,
  },
  {
    id: 's2',
    source_type: 'spotify',
    source_name: 'Acquired',
    category: 'startups',
    title: "The Stripe Story: Building the Internet's Financial Infrastructure",
    excerpt: "Ben and David go deep on Stripe's decade-long arc from a two-person Irish startup to a $65B company processing hundreds of billions in payments annually.",
    url: 'https://open.spotify.com/episode/mock-s2',
    thumbnail_url: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&q=80',
    author: 'Ben Gilbert & David Rosenthal',
    duration: 14820,
    published_at: '2026-04-25T09:00:00.000Z',
    fetched_at: NOW,
    created_at: NOW,
  },
  {
    id: 's3',
    source_type: 'rss',
    source_name: 'Sifted',
    category: 'startups',
    title: 'EU Startup Monitor 2026: €42B raised in Q1 — but where is the money going?',
    excerpt: 'Despite a global pullback in late-stage venture, European early-stage activity hit a five-year high. Climate-tech and B2B SaaS dominate the deal flow.',
    url: 'https://sifted.eu/articles/mock-s3',
    thumbnail_url: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&q=80',
    author: 'Sifted Editorial',
    published_at: '2026-04-26T07:30:00.000Z',
    fetched_at: NOW,
    created_at: NOW,
  },
  {
    id: 's4',
    source_type: 'forum',
    source_name: 'Hacker News',
    category: 'startups',
    title: "Ask HN: What's the most underrated European startup ecosystem right now?",
    excerpt: 'Thread discussing Warsaw, Tallinn, and Bucharest as emerging hubs. 312 comments.',
    url: 'https://news.ycombinator.com/item?id=mock-s4',
    author: 'HN Community',
    published_at: '2026-04-25T18:22:00.000Z',
    fetched_at: NOW,
    created_at: NOW,
  },
  // ── Frontend ─────────────────────────────────────────────────────────────
  {
    id: 'f1',
    source_type: 'youtube',
    source_name: 'Theo — t3.gg',
    category: 'frontend',
    title: 'React 19 Compiler: What Actually Changes in Your Codebase',
    excerpt: 'Theo walks through the React Compiler in production, showing before/after render profiles and which patterns benefit most from automatic memoization.',
    url: 'https://www.youtube.com/watch?v=mock-f1',
    thumbnail_url: 'https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=800&q=80',
    author: 'Theo Browne',
    duration: 2156,
    published_at: '2026-04-26T03:00:00.000Z',
    fetched_at: NOW,
    created_at: NOW,
  },
  {
    id: 'f2',
    source_type: 'spotify',
    source_name: 'Syntax.fm',
    category: 'frontend',
    title: "CSS in 2026 — Container Queries, @scope, and What's Coming Next",
    excerpt: 'Wes and Scott cover the CSS features that shipped this year, which ones are actually worth using in production, and a preview of what\'s in the pipeline.',
    url: 'https://open.spotify.com/episode/mock-f2',
    thumbnail_url: 'https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?w=400&q=80',
    author: 'Wes Bos & Scott Tolinski',
    duration: 4320,
    published_at: '2026-04-25T12:00:00.000Z',
    fetched_at: NOW,
    created_at: NOW,
  },
  {
    id: 'f3',
    source_type: 'medium',
    source_name: 'CSS-Tricks',
    category: 'frontend',
    title: 'Why I stopped using Tailwind and what I learned from the switch',
    excerpt: "After three years of Tailwind-first development, one engineer's honest account of moving back to CSS Modules for a large design system — and what each approach actually costs.",
    url: 'https://css-tricks.com/mock-f3',
    thumbnail_url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80',
    author: 'Robin Rendle',
    published_at: '2026-04-24T15:00:00.000Z',
    fetched_at: NOW,
    created_at: NOW,
  },
  {
    id: 'f4',
    source_type: 'rss',
    source_name: 'web.dev',
    category: 'frontend',
    title: 'Interop 2026: The browser features all vendors agreed to standardize',
    excerpt: 'The annual cross-browser interoperability project reveals its focus areas for the year: CSS anchor positioning, View Transitions Level 2, and the Popover API.',
    url: 'https://web.dev/blog/interop-2026',
    thumbnail_url: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80',
    author: 'Chrome DevRel',
    published_at: '2026-04-26T08:00:00.000Z',
    fetched_at: NOW,
    created_at: NOW,
  },
  // ── Backend ──────────────────────────────────────────────────────────────
  {
    id: 'b1',
    source_type: 'youtube',
    source_name: 'Fireship',
    category: 'backend',
    title: 'Bun 2.0 vs Node.js: I tested 47 real-world scenarios',
    excerpt: "Fireship puts Bun's new major release through a gauntlet of HTTP servers, database connections, and file I/O benchmarks against Node.js 24 LTS.",
    url: 'https://www.youtube.com/watch?v=mock-b1',
    thumbnail_url: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=800&q=80',
    author: 'Jeff Delaney',
    duration: 892,
    published_at: '2026-04-26T02:00:00.000Z',
    fetched_at: NOW,
    created_at: NOW,
  },
  {
    id: 'b2',
    source_type: 'spotify',
    source_name: 'JS Party',
    category: 'backend',
    title: 'The State of Node.js 2026: What the core team is actually working on',
    excerpt: 'A Node.js core contributor joins the show to discuss the performance roadmap, the future of CommonJS, and why the permission system matters more than you think.',
    url: 'https://open.spotify.com/episode/mock-b2',
    thumbnail_url: 'https://images.unsplash.com/photo-1484417894907-623942c8ee29?w=400&q=80',
    author: 'Changelog Media',
    duration: 5580,
    published_at: '2026-04-25T10:00:00.000Z',
    fetched_at: NOW,
    created_at: NOW,
  },
  {
    id: 'b3',
    source_type: 'rss',
    source_name: 'Hono Blog',
    category: 'backend',
    title: 'Hono v5: RPC client, middleware redesign, and full Cloudflare Workflows support',
    excerpt: 'The lightweight JavaScript framework hits its fifth major version with a redesigned middleware chain and a type-safe RPC client that generates types from your routes.',
    url: 'https://hono.dev/blog/mock-b3',
    thumbnail_url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80',
    author: 'Yusuke Wada',
    published_at: '2026-04-24T08:00:00.000Z',
    fetched_at: NOW,
    created_at: NOW,
  },
  {
    id: 'b4',
    source_type: 'forum',
    source_name: 'Hacker News',
    category: 'backend',
    title: 'Bun now benchmarks faster than some Rust HTTP servers — is this expected?',
    excerpt: 'Community discussion on Bun\'s HTTP performance, JavaScriptCore optimizations, and what the benchmarks actually measure. 487 comments.',
    url: 'https://news.ycombinator.com/item?id=mock-b4',
    author: 'HN Community',
    published_at: '2026-04-25T20:00:00.000Z',
    fetched_at: NOW,
    created_at: NOW,
  },
  // ── AI News ──────────────────────────────────────────────────────────────
  {
    id: 'a1',
    source_type: 'youtube',
    source_name: 'AI Explained',
    category: 'ai',
    title: 'Claude 4 Opus vs GPT-5: 90-day independent benchmark results',
    excerpt: 'A systematic comparison across reasoning, coding, and long-context tasks. The results are more nuanced than the headline numbers suggest — especially for agentic use cases.',
    url: 'https://www.youtube.com/watch?v=mock-a1',
    thumbnail_url: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80',
    author: 'AI Explained',
    duration: 2934,
    published_at: '2026-04-26T05:00:00.000Z',
    fetched_at: NOW,
    created_at: NOW,
  },
  {
    id: 'a2',
    source_type: 'rss',
    source_name: 'Anthropic Blog',
    category: 'ai',
    title: 'Introducing Claude 4.5: Extended context, improved reasoning, and new safety research',
    excerpt: "Anthropic's latest model release includes a 400k context window, significant improvements on the MMLU-Pro benchmark, and new Constitutional AI research findings.",
    url: 'https://anthropic.com/blog/mock-a2',
    thumbnail_url: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80',
    author: 'Anthropic',
    published_at: '2026-04-26T08:00:00.000Z',
    fetched_at: NOW,
    created_at: NOW,
  },
  {
    id: 'a3',
    source_type: 'rss',
    source_name: 'Google DeepMind',
    category: 'ai',
    title: 'Gemini 2.5 Ultra: Technical report and benchmark breakdown',
    excerpt: 'DeepMind publishes the technical details behind their latest flagship model, including architecture decisions, training data composition, and performance on scientific reasoning tasks.',
    url: 'https://deepmind.google/blog/mock-a3',
    thumbnail_url: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&q=80',
    author: 'Google DeepMind',
    published_at: '2026-04-25T14:00:00.000Z',
    fetched_at: NOW,
    created_at: NOW,
  },
  {
    id: 'a4',
    source_type: 'medium',
    source_name: 'Towards Data Science',
    category: 'ai',
    title: "The race to AGI just got real — here's what the labs aren't saying publicly",
    excerpt: 'An analysis of the gap between what AI labs publish and what their internal benchmarks likely show, based on public statements, hiring patterns, and researcher departures.',
    url: 'https://towardsdatascience.com/mock-a4',
    thumbnail_url: 'https://images.unsplash.com/photo-1655720828018-edd2daec9349?w=800&q=80',
    author: 'Tim Dettmers',
    published_at: '2026-04-24T11:00:00.000Z',
    fetched_at: NOW,
    created_at: NOW,
  },
  // ── AI Dev ───────────────────────────────────────────────────────────────
  {
    id: 'd1',
    source_type: 'youtube',
    source_name: 'Theo — t3.gg',
    category: 'ai-dev',
    title: "I used Claude Code for 60 days straight — here's my honest review",
    excerpt: 'After 60 days of daily Claude Code usage across five production projects, Theo breaks down what actually works, what breaks, and whether the subscription is worth it for full-time engineers.',
    url: 'https://www.youtube.com/watch?v=mock-d1',
    thumbnail_url: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800&q=80',
    author: 'Theo Browne',
    duration: 1823,
    published_at: '2026-04-26T01:00:00.000Z',
    fetched_at: NOW,
    created_at: NOW,
  },
  {
    id: 'd2',
    source_type: 'spotify',
    source_name: 'Latent Space',
    category: 'ai-dev',
    title: 'The Cursor Founders on building an AI IDE from scratch (and what comes next)',
    excerpt: "Anysphere's co-founders discuss the architectural decisions behind Cursor, why they bet on language models for code editing before anyone else, and their vision for the next generation of developer tools.",
    url: 'https://open.spotify.com/episode/mock-d2',
    thumbnail_url: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=800&q=80',
    author: 'Alessio Fanelli & Swyx',
    duration: 6840,
    published_at: '2026-04-25T08:00:00.000Z',
    fetched_at: NOW,
    created_at: NOW,
  },
  {
    id: 'd3',
    source_type: 'rss',
    source_name: 'Vercel Blog',
    category: 'ai-dev',
    title: 'MCP is becoming the USB-C of AI integrations — and what that means for your stack',
    excerpt: 'The Model Context Protocol has quietly become the default way AI agents communicate with tools. We look at adoption patterns, the emerging ecosystem, and how to build MCP-native apps.',
    url: 'https://vercel.com/blog/mock-d3',
    thumbnail_url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80',
    author: 'Lee Robinson',
    published_at: '2026-04-26T06:30:00.000Z',
    fetched_at: NOW,
    created_at: NOW,
  },
  {
    id: 'd4',
    source_type: 'forum',
    source_name: 'Hacker News',
    category: 'ai-dev',
    title: 'We let Claude Code complete our senior engineering interview — it passed',
    excerpt: "A startup ran their standard senior engineer take-home through Claude Code unassisted. The results, what it got right, what it missed, and why they're rethinking the interview. 621 comments.",
    url: 'https://news.ycombinator.com/item?id=mock-d4',
    author: 'HN Community',
    published_at: '2026-04-25T22:00:00.000Z',
    fetched_at: NOW,
    created_at: NOW,
  },
]
